#ifndef SHADER_SHARED_H
#define SHADER_SHARED_H

// descriptor idx
#define VK_DESC_STORAGE					0
#define VK_DESC_UNIFORM					0
#define VK_DESC_TEXTURE0				1
#define VK_DESC_TEXTURE1				2
#define VK_DESC_TEXTURE2				3
#define VK_DESC_FOG_COLLAPSE			4
#define VK_DESC_COUNT					5

#define VK_DESC_TEXTURE_BASE			VK_DESC_TEXTURE0
#define VK_DESC_FOG_ONLY				VK_DESC_TEXTURE1
#define VK_DESC_FOG_DLIGHT				VK_DESC_TEXTURE1

// uniform binding idx
#define VK_DESC_UNIFORM_MAIN_BINDING	0
#define VK_DESC_UNIFORM_CAMERA_BINDING	1
#define VK_DESC_UNIFORM_ENTITY_BINDING	2
#define VK_DESC_UNIFORM_BONES_BINDING	3
#define VK_DESC_UNIFORM_FOGS_BINDING	4
#define VK_DESC_UNIFORM_GLOBAL_BINDING	5
#define VK_DESC_UNIFORM_COUNT			6

#endif