#!/usr/bin/env python3
"""Emit the placeholder-summary review queue as a checklist.

A placeholder summary is the generator's fallback wording, used when no
behavior description could be proven from source, xdocs, or the shipped
documentation.  They are real entries with real registration evidence; only the
prose is missing.  This orders the backlog so it can be worked down where the
payoff is highest and the evidence is closest to hand:

  1. TaystJK-origin entries first -- this project's own additions, which nobody
     upstream is going to document.
  2. Then entries that already have an in-game xdocs entry, because the wording
     can be taken from it rather than reconstructed from the code.
  3. Then alphabetically, so the file has a stable diff between runs.

The output is a working checklist, deliberately not a site page.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

# The generator's fallback wording: "Controls `cg_foo` in the cgame module.",
# and the command-side equivalents.
PLACEHOLDER = re.compile(r"^\w+ .* in the .* module\b")
ORIGIN_LABELS = {
    "taystjk": "TaystJK", "eternaljk": "EternalJK", "japro": "jaPRO",
    "jk2mv": "JK2MV", "newjk": "NewJK / NewMod", "rend2": "rend2",
    "vulkan": "Vulkan", "openjk": "OpenJK", "basejka": "Base Jedi Academy",
    "quake3": "Quake III lineage", "unknown": "Unknown",
}


def origin_of(entry: dict[str, Any]) -> str:
    origin = entry.get("origin") or {}
    return origin.get("source") or "unknown"


def is_placeholder(entry: dict[str, Any]) -> bool:
    return bool(PLACEHOLDER.match((entry.get("summary") or "").strip()))


def sort_key(entry: dict[str, Any]) -> tuple[int, int, str]:
    return (
        0 if origin_of(entry) == "taystjk" else 1,
        0 if entry.get("xdocs") else 1,
        entry["name"].casefold(),
    )


def render(entries: list[dict[str, Any]], total: int) -> str:
    lines = [
        "# Placeholder summary triage",
        "",
        f"{len(entries)} of {total} reference entries carry a generated placeholder",
        "summary rather than a described one. Generated by "
        "`python3 tools/cvar_audit/triage.py`; do not hand-edit.",
        "",
        "Ordered by TaystJK-origin first, then by whether an in-game xdocs entry",
        "already supplies wording, then alphabetically.",
        "",
        "Write the replacement into `tools/cvar_audit/overrides.json` under the",
        "entry's name, then regenerate. Do not edit `_data/` directly.",
        "",
    ]
    for group, label in ((0, "TaystJK-origin"), (1, "Other origins")):
        section = [entry for entry in entries if sort_key(entry)[0] == group]
        if not section:
            continue
        lines.extend([f"## {label} ({len(section)})", ""])
        for entry in section:
            marks = []
            if entry.get("xdocs"):
                marks.append("xdocs")
            if entry.get("menu_entries"):
                marks.append("menu")
            suffix = f" — {', '.join(marks)}" if marks else ""
            origin = ORIGIN_LABELS.get(origin_of(entry), origin_of(entry))
            lines.append(
                f"- [ ] `{entry['name']}` ({entry['kind']}, {entry['module']}, {origin}){suffix}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cvars", default="_data/cvars.json", type=Path)
    parser.add_argument("--commands", default="_data/commands.json", type=Path)
    parser.add_argument("--output", default="tools/cvar_audit/placeholder-triage.md", type=Path)
    args = parser.parse_args()

    entries = json.loads(args.cvars.read_text()) + json.loads(args.commands.read_text())
    pending = sorted((entry for entry in entries if is_placeholder(entry)), key=sort_key)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(pending, len(entries)))
    taystjk = sum(1 for entry in pending if origin_of(entry) == "taystjk")
    with_xdocs = sum(1 for entry in pending if entry.get("xdocs"))
    print(
        f"{len(pending)} placeholder summaries of {len(entries)} entries "
        f"({taystjk} TaystJK-origin, {with_xdocs} with xdocs wording) -> {args.output}"
    )


if __name__ == "__main__":
    main()
